# Generated by Django 3.2.9 on 2021-11-16 09:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("some_app", "0002_product_time_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="title",
        ),
    ]
