# Generated by Django 3.2.9 on 2021-11-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("some_app", "0003_remove_product_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="time_created",
            field=models.DateTimeField(),
        ),
    ]
